# PyInstaller spec — builds Phishing Detector into a standalone .exe
block_cipher = None

a = Analysis(
    ['src/gui.py'],
    pathex=['src'],
    binaries=[],
    datas=[
        ('samples', 'samples'),
    ],
    hiddenimports=[
        'analyzer',
        'header_analysis',
        'url_analysis',
        'content_analysis',
        'dns_analysis',
        'virustotal',
        'dns',
        'dns.resolver',
        'dns.rdatatype',
        'dns.rdataclass',
        'dns.name',
        'dns.message',
        'dns.query',
        'dns.exception',
        'requests',
        'email',
        'email.policy',
        'tkinter',
        'tkinter.ttk',
        'tkinter.filedialog',
        'tkinter.scrolledtext',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='PhishingDetector',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=None,
)
